### ISSUE TITLE
System default file explorers

### ISSUE THREAD

**Issue by WyattRoss** [ezasm-org/EzASM#48]
As an end user
I want loading and saving files to use my system default file explorer
So that I can save and load files while having to interact with swing as little as possible

**Description**
Replace the current save and load file dialogs with something that doesn't use swing. If the user doesn't have a graphical file picker on their system for whatever reason I guess falling back onto swing makes sense.

**Comment by TrevorBrunette** [comment]
I found two ways of accomplishing this idea:
use the native file explorer (via awt) if it exists:
```Java
new java.awt.FileDialog((java.awt.Frame) null).setVisible(true);
```
or theme the Java GUI to have the look and feel of the OS:
```Java
try {
    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
}catch(Exception ex) {
    ex.printStackTrace();
}
```

**Comment by TrevorBrunette** [comment]
Should this be closed as wont fix?

**Comment by TrevorBrunette** [comment]
Unable to implement
