### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by WyattRoss** [ezasm-org/EzASM#86]
**As an** end user
**I want** an timing based autosave feature
**So that** I don't have to worry as much about losing my work.

**Request Description**
If I'm editing a named file (i.e. a file that already exists, or one that I created with save as), I want the program to automatically save periodically. A user should be able to toggle this feature on or off, as well as change the interval at which the program autosaves.

This feature does not make sense to implement until after #80 is done

**Comment by TrevorBrunette** [comment]
Closed by #137
