### ISSUE TITLE
Icon/Favicon

### ISSUE THREAD

**Issue by WyattRoss** [ezasm-org/EzASM#90]
**As a** developer
**I want** the app and favicon of the app to not be the java penguin
**So that** the app looks better

**Request Description**
Make a logo, make presentable, change the app so the toolbar icon and app favicon are that logo instead of [Duke](https://www.oracle.com/a/ocom/img/rc24-duke-java-mascot.jpg).

**Comment by TrevorBrunette** [comment]
Closed by #118
